micronaut:
  application.name: rawdata-converter-app-csv
  server:
    port: 28090
    netty.access-logger.enabled: true

logger.levels:
  no.ssb.rawdata.converter: DEBUG
  io.micronaut.security: DEBUG

endpoints:
  all:
    sensitive: false
  prometheus:
    sensitive: false

services:
  dapla-oauth:
    token-provider: mock
  dapla-data-access:
    host: data-access.dapla.svc.cluster.local
    port: 10138
  dapla-metadata-distributor:
    host: metadata-distributor.dapla.svc.cluster.local
    port: 10168
    project-id: prod-bip
    topic: metadata-distributor-dataset-updates

pseudo-secrets:
  secret1:
    content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
    type: AES256

rawdata.sources:
  fs-kag:
    encryption:
      key: blah
      salt: blahblah
    rawdata-client:
      provider: filesystem
      local-temp-folder: temp
      avro-file:
        max.seconds: 3600
        max.bytes: 10485760
        sync.interval: 500000
      filesystem:
        storage-folder: ../localenv/rawdata/ssb-rawdata-prod-kag
      listing:
        min-interval-seconds: 0

  fs-orbof:
    rawdata-client:
      provider: filesystem
      local-temp-folder: temp
      avro-file:
        max.seconds: 3600
        max.bytes: 10485760
        sync.interval: 500000
      filesystem:
        storage-folder: ../localenv/rawdata/ssb-rawdata-dev-orbof
      listing:
        min-interval-seconds: 0


rawdata.converter:
  job-scheduler:
    max-concurrent-jobs: 10
  jobs:
    base:
      prototype: true
      debug:
        dryrun: false
        development-mode: true
        log-rawdata-content-allowed: true
        store-failed-messages: true
        failed-messages-storage-path: /tmp/failed-messages
        store-all-messages: false
        all-messages-storage-path: ./rawdata-messages-output
      converter-settings:
        rawdata-samples: 1
        max-records-before-flush: 1000000
        max-seconds-before-flush: 300
      target-storage:
        type: filesystem
        root: file://../localenv/datastore
      target-dataset:
        valuation: INTERNAL
        type: BOUNDED
        publish-metadata: false
      pseudo-rules:
          - name: fodselsnummer
            pattern: '**/{folkeregisteridentifikator,foedselsEllerDNummer,relatertVedSivilstand,relatertPerson}'
            func: fpe-fnr(secret1)

    job-blah:
      parent: base
      active-by-default: false
      rawdata-source:
        name: fs-kag
        topic: 20192020-kag-resultat-202009211735
        initial-position: 01EJRMWMEE000000000000004D
      target-storage:
        path: /kilde/kag/karakter/raadata/202009191130
        version: 1598553650000
      pseudo-rules:
          - name: navn
            pattern: '**/{navn}'
            func: fpe-anychar(secret1)
          - name: organisasjonsnummer
            pattern: '**/organisasjonsnummer'
            func: fpe-digits(secret1)

    job-orbof:
      parent: base
      active-by-default: true
      rawdata-source:
        name: fs-orbof
        topic: orbof-r10-m12-dryrun
        initial-position: FIRST
      target-storage:
        path: /kilde/orbof/test
        version: 1598553650000
      pseudo-rules:
        - name: OrbofLnr
          pattern: '**/{OrbofLnr}'
          func: fpe-anychar(secret1)

